In [3]:
import numpy as np
import pandas as pd

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hasibur013/diabetes-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/hasibur013/diabetes-dataset/1.archive...

100%|██████████| 8.93k/8.93k [00:00<00:00, 6.00MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/hasibur013/diabetes-dataset/versions/1

The previous error indicated that `diabetes.csv` was not found. Let's list the contents of the downloaded dataset directory to find the correct CSV file name.

In [5]:
import os
print(os.listdir(path))

['diabetes_dataset.csv']

In [6]:
import os
df = pd.read_csv(os.path.join(path, 'diabetes_dataset.csv'))

In [7]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [9]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [10]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [11]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [13]:
X = scaler.fit_transform(X)

In [14]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [15]:
X.shape

(768, 8)

In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(X,y, test_size = 0.2 , random_state = 1)

In [17]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [18]:
model = Sequential()

model.add(Dense(32,activation = 'relu', input_dim=8))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
history = model.fit(X_train, y_train , batch_size =32, epochs=100 , validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6645 - loss: 0.6196 - val_accuracy: 0.6948 - val_loss: 0.6039
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6873 - loss: 0.5827 - val_accuracy: 0.7208 - val_loss: 0.5726
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7020 - loss: 0.5557 - val_accuracy: 0.7273 - val_loss: 0.5489
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5348 - val_accuracy: 0.7727 - val_loss: 0.5307
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7345 - loss: 0.5182 - val_accuracy: 0.7987 - val_loss: 0.5157
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5050 - val_accuracy: 0.7922 - val_loss: 0.5037
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.4944 - val_accuracy: 0.8052 - val_loss: 0.4954
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4867 - val_accuracy: 0.7987 - val_loss: 0.4902
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4790 - val_accuracy: 0.7922 - val_loss: 0.4850
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4745 - val_accuracy: 0.7922 - val_loss: 0.4814
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4692 - val_accuracy: 0.7987 - val_loss: 0.4785
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4658 - val_accuracy: 0.7922 - val_loss: 0.4765
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4622 - val_accuracy: 0.7857 - val_loss: 0.4746
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4597 - val_accuracy: 0.7792 - val_loss: 0.4742
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4570 - val_accuracy: 0.7792 - val_loss: 0.4733
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4551 - val_accuracy: 0.7792 - val_loss: 0.4713
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4536 - val_accuracy: 0.7857 - val_loss: 0.4709
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4517 - val_accuracy: 0.7857 - val_loss: 0.4715
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4500 - val_accuracy: 0.7857 - val_loss: 0.4707
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4490 - val_accuracy: 0.7857 - val_loss: 0.4708
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4484 - val_accuracy: 0.7792 - val_loss: 0.4705
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4474 - val_accuracy: 0.7792 - val_loss: 0.4701
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4468 - val_accuracy: 0.7792 - val_loss: 0.4702
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4457 - val_accuracy: 0.7792 - val_loss: 0.4694
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4456 - val_accuracy: 0.7727 - val_loss: 0.4712
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4449 - val_accuracy: 0.7727 - val_loss: 0.4710
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4435 - val_accuracy: 0.7792 - val_loss: 0.4713
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4432 - val_accuracy: 0.7792 - val_loss: 0.4713
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4425 - val_accuracy: 0.7792 - val_loss: 0.4702
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4416 - val_accuracy: 0.7792 - val_loss: 0.4710
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4410 - val_accuracy: 0.7792 - val_loss: 0.4703
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4404 - val_accuracy: 0.7727 - val_loss: 0.4717
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4396 - val_accuracy: 0.7727 - val_loss: 0.4702
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4397 - val_accuracy: 0.7792 - val_loss: 0.4694
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4387 - val_accuracy: 0.7727 - val_loss: 0.4699
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4383 - val_accuracy: 0.7727 - val_loss: 0.4708
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4379 - val_accuracy: 0.7792 - val_loss: 0.4705
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4375 - val_accuracy: 0.7792 - val_loss: 0.4705
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4369 - val_accuracy: 0.7857 - val_loss: 0.4705
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4370 - val_accuracy: 0.7857 - val_loss: 0.4704
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4360 - val_accuracy: 0.7792 - val_loss: 0.4700
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4355 - val_accuracy: 0.7857 - val_loss: 0.4711
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4355 - val_accuracy: 0.7922 - val_loss: 0.4696
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4346 - val_accuracy: 0.7857 - val_loss: 0.4708
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4341 - val_accuracy: 0.7857 - val_loss: 0.4701
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4338 - val_accuracy: 0.7857 - val_loss: 0.4692
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4336 - val_accuracy: 0.7857 - val_loss: 0.4702
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4328 - val_accuracy: 0.7922 - val_loss: 0.4691
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4323 - val_accuracy: 0.7857 - val_loss: 0.4688
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4323 - val_accuracy: 0.7857 - val_loss: 0.4688
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4315 - val_accuracy: 0.7857 - val_loss: 0.4694
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4313 - val_accuracy: 0.7987 - val_loss: 0.4698
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4309 - val_accuracy: 0.7987 - val_loss: 0.4692
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4304 - val_accuracy: 0.7987 - val_loss: 0.4699
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4298 - val_accuracy: 0.7987 - val_loss: 0.4699
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4299 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4289 - val_accuracy: 0.7922 - val_loss: 0.4693
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4285 - val_accuracy: 0.7987 - val_loss: 0.4690
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4283 - val_accuracy: 0.7987 - val_loss: 0.4696
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4276 - val_accuracy: 0.7987 - val_loss: 0.4692
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4276 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4271 - val_accuracy: 0.7987 - val_loss: 0.4686
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4268 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4266 - val_accuracy: 0.7987 - val_loss: 0.4704
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4265 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4255 - val_accuracy: 0.7922 - val_loss: 0.4708
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4257 - val_accuracy: 0.7922 - val_loss: 0.4697
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4252 - val_accuracy: 0.7987 - val_loss: 0.4678
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4247 - val_accuracy: 0.7987 - val_loss: 0.4678
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4243 - val_accuracy: 0.7987 - val_loss: 0.4673
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4240 - val_accuracy: 0.7987 - val_loss: 0.4671
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4239 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4233 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4227 - val_accuracy: 0.7987 - val_loss: 0.4662
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4223 - val_accuracy: 0.7922 - val_loss: 0.4666
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4232 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4221 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4217 - val_accuracy: 0.7922 - val_loss: 0.4660
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4215 - val_accuracy: 0.7922 - val_loss: 0.4664
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4207 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4203 - val_accuracy: 0.7987 - val_loss: 0.4660
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4207 - val_accuracy: 0.7987 - val_loss: 0.4647
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4196 - val_accuracy: 0.7987 - val_loss: 0.4655
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4199 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4197 - val_accuracy: 0.7987 - val_loss: 0.4665
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4188 - val_accuracy: 0.7987 - val_loss: 0.4671
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4194 - val_accuracy: 0.7987 - val_loss: 0.4645
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4186 - val_accuracy: 0.7987 - val_loss: 0.4644
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4181 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4178 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4181 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4173 - val_accuracy: 0.7987 - val_loss: 0.4639
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4172 - val_accuracy: 0.7987 - val_loss: 0.4645
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4171 - val_accuracy: 0.7987 - val_loss: 0.4656
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4173 - val_accuracy: 0.7987 - val_loss: 0.4659
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4163 - val_accuracy: 0.7987 - val_loss: 0.4652
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4160 - val_accuracy: 0.7987 - val_loss: 0.4654
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4161 - val_accuracy: 0.7987 - val_loss: 0.4653
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4154 - val_accuracy: 0.8052 - val_loss: 0.4657
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8062 - loss: 0.4150 - val_accuracy: 0.8052 - val_loss: 0.4659

# Now we will do the Following steps
#### 1.  how to select appropriate optimizer
#### 2. No. of Nodes in a layer
#### 3. How to select no of layers
#### 4. All in ONe Model

In [21]:
!pip install -q -U keras-tuner
import keras_tuner as kt
print("The Keras-Tuner Library Successfully Installed")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.3 MB/s eta 0:00:00
The Keras-Tuner Library Successfully Installed

In [22]:
def build_model(hp):
    model = Sequential()
    model.add(Dense(32, activation='relu',input_dim=8))
    model.add(Dense(1, activation='sigmoid'))

    optimizer = hp.Choice('optimzer',values = ['adam', 'sgd', 'rmsprop', 'adadelta'])

    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [23]:
tuner = kt.RandomSearch(build_model,
                       objective = 'val_accuracy',
                       max_trials=5)

In [24]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.6623376607894897

Best val_accuracy So Far: 0.7597402334213257
Total elapsed time: 00h 00m 20s

In [25]:
tuner.get_best_hyperparameters()[0].values

{'optimzer': 'adam'}

In [26]:
model =  tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [27]:
model.fit(X_train,y_train,batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.7182 - loss: 0.5457 - val_accuracy: 0.7597 - val_loss: 0.5311
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7329 - loss: 0.5260 - val_accuracy: 0.7727 - val_loss: 0.5138
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7410 - loss: 0.5121 - val_accuracy: 0.7727 - val_loss: 0.5000
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7492 - loss: 0.5023 - val_accuracy: 0.7792 - val_loss: 0.4901
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7541 - loss: 0.4939 - val_accuracy: 0.7857 - val_loss: 0.4832
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7638 - loss: 0.4874 - val_accuracy: 0.7727 - val_loss: 0.4758
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7704 - loss: 0.4815 - val_accuracy: 0.7727 - val_loss: 0.4721
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7736 - loss: 0.4769 - val_accuracy: 0.7727 - val_loss: 0.4669
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7736 - loss: 0.4725 - val_accuracy: 0.7727 - val_loss: 0.4627
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7736 - loss: 0.4687 - val_accuracy: 0.7727 - val_loss: 0.4598
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7769 - loss: 0.4660 - val_accuracy: 0.7727 - val_loss: 0.4575
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7769 - loss: 0.4638 - val_accuracy: 0.7792 - val_loss: 0.4560
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7736 - loss: 0.4613 - val_accuracy: 0.7792 - val_loss: 0.4544
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7752 - loss: 0.4598 - val_accuracy: 0.7792 - val_loss: 0.4538
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7720 - loss: 0.4581 - val_accuracy: 0.7792 - val_loss: 0.4529
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7720 - loss: 0.4571 - val_accuracy: 0.7727 - val_loss: 0.4527
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7801 - loss: 0.4562 - val_accuracy: 0.7857 - val_loss: 0.4530
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7801 - loss: 0.4543 - val_accuracy: 0.7727 - val_loss: 0.4524
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7834 - loss: 0.4536 - val_accuracy: 0.7857 - val_loss: 0.4538
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4524 - val_accuracy: 0.7857 - val_loss: 0.4528
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7818 - loss: 0.4514 - val_accuracy: 0.7857 - val_loss: 0.4536
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7818 - loss: 0.4504 - val_accuracy: 0.7857 - val_loss: 0.4531
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7850 - loss: 0.4494 - val_accuracy: 0.7857 - val_loss: 0.4531
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7834 - loss: 0.4484 - val_accuracy: 0.7857 - val_loss: 0.4514
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7866 - loss: 0.4479 - val_accuracy: 0.7857 - val_loss: 0.4507
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.7834 - loss: 0.4474 - val_accuracy: 0.7857 - val_loss: 0.4505
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7834 - loss: 0.4464 - val_accuracy: 0.7857 - val_loss: 0.4498
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7818 - loss: 0.4457 - val_accuracy: 0.7857 - val_loss: 0.4507
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4448 - val_accuracy: 0.7857 - val_loss: 0.4505
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4448 - val_accuracy: 0.7857 - val_loss: 0.4497
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4434 - val_accuracy: 0.7857 - val_loss: 0.4494
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4432 - val_accuracy: 0.7857 - val_loss: 0.4484
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4424 - val_accuracy: 0.7857 - val_loss: 0.4486
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4427 - val_accuracy: 0.7857 - val_loss: 0.4491
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4412 - val_accuracy: 0.7857 - val_loss: 0.4489
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4407 - val_accuracy: 0.7857 - val_loss: 0.4494
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4402 - val_accuracy: 0.7857 - val_loss: 0.4486
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4398 - val_accuracy: 0.7857 - val_loss: 0.4485
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4391 - val_accuracy: 0.7857 - val_loss: 0.4483
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4388 - val_accuracy: 0.7857 - val_loss: 0.4472
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4387 - val_accuracy: 0.7857 - val_loss: 0.4491
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4381 - val_accuracy: 0.7857 - val_loss: 0.4484
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4375 - val_accuracy: 0.7857 - val_loss: 0.4493
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4368 - val_accuracy: 0.7857 - val_loss: 0.4484
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4365 - val_accuracy: 0.7857 - val_loss: 0.4480
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4358 - val_accuracy: 0.7857 - val_loss: 0.4488
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4355 - val_accuracy: 0.7857 - val_loss: 0.4491
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4353 - val_accuracy: 0.7857 - val_loss: 0.4502
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4346 - val_accuracy: 0.7857 - val_loss: 0.4495
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4342 - val_accuracy: 0.7857 - val_loss: 0.4479
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4339 - val_accuracy: 0.7857 - val_loss: 0.4485
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4335 - val_accuracy: 0.7857 - val_loss: 0.4498
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4334 - val_accuracy: 0.7857 - val_loss: 0.4494
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4328 - val_accuracy: 0.7857 - val_loss: 0.4501
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4326 - val_accuracy: 0.7857 - val_loss: 0.4518
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4322 - val_accuracy: 0.7857 - val_loss: 0.4497
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4317 - val_accuracy: 0.7857 - val_loss: 0.4494
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4315 - val_accuracy: 0.7857 - val_loss: 0.4505
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4307 - val_accuracy: 0.7857 - val_loss: 0.4501
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4308 - val_accuracy: 0.7922 - val_loss: 0.4504
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4299 - val_accuracy: 0.7922 - val_loss: 0.4510
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4298 - val_accuracy: 0.7857 - val_loss: 0.4499
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4292 - val_accuracy: 0.7987 - val_loss: 0.4501
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4288 - val_accuracy: 0.7922 - val_loss: 0.4499
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4291 - val_accuracy: 0.7857 - val_loss: 0.4504
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4283 - val_accuracy: 0.7922 - val_loss: 0.4506
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4279 - val_accuracy: 0.7922 - val_loss: 0.4499
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4278 - val_accuracy: 0.7857 - val_loss: 0.4506
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4273 - val_accuracy: 0.7922 - val_loss: 0.4491
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4271 - val_accuracy: 0.7922 - val_loss: 0.4495
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4267 - val_accuracy: 0.7922 - val_loss: 0.4488
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4261 - val_accuracy: 0.7857 - val_loss: 0.4491
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4260 - val_accuracy: 0.7922 - val_loss: 0.4492
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4256 - val_accuracy: 0.7987 - val_loss: 0.4488
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4257 - val_accuracy: 0.7922 - val_loss: 0.4494
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4250 - val_accuracy: 0.7987 - val_loss: 0.4494
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4245 - val_accuracy: 0.8117 - val_loss: 0.4492
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4242 - val_accuracy: 0.8052 - val_loss: 0.4501
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4242 - val_accuracy: 0.8052 - val_loss: 0.4500
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4236 - val_accuracy: 0.7987 - val_loss: 0.4508
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4234 - val_accuracy: 0.8052 - val_loss: 0.4503
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4228 - val_accuracy: 0.7922 - val_loss: 0.4508
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4227 - val_accuracy: 0.7922 - val_loss: 0.4499
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4225 - val_accuracy: 0.7922 - val_loss: 0.4516
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4221 - val_accuracy: 0.8052 - val_loss: 0.4527
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4220 - val_accuracy: 0.7987 - val_loss: 0.4516
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4212 - val_accuracy: 0.7987 - val_loss: 0.4519
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4216 - val_accuracy: 0.8052 - val_loss: 0.4503
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4212 - val_accuracy: 0.8117 - val_loss: 0.4523
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4209 - val_accuracy: 0.7987 - val_loss: 0.4521
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4203 - val_accuracy: 0.7987 - val_loss: 0.4525
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4196 - val_accuracy: 0.7987 - val_loss: 0.4511
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4193 - val_accuracy: 0.7987 - val_loss: 0.4510
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4200 - val_accuracy: 0.7987 - val_loss: 0.4524

In [28]:
def build_model(hp):
    model = Sequential()

    model.add(Dense(72,activation='relu', input_dim=8))

    for i in range(hp.Int('num_layers', min_value=1,max_value=10)):
      model.add(Dense(72,activation='relu'))

    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [29]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='num_layers')

In [30]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8116883039474487

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 11s

In [31]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 7}

In [32]:
model= tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 20 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [33]:
model.fit(X_train,y_train,batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.7557 - loss: 0.4929 - val_accuracy: 0.7662 - val_loss: 0.5213
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7769 - loss: 0.4619 - val_accuracy: 0.8052 - val_loss: 0.4838
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4509 - val_accuracy: 0.7987 - val_loss: 0.4894
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4444 - val_accuracy: 0.7792 - val_loss: 0.5292
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4368 - val_accuracy: 0.7727 - val_loss: 0.5212
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4180 - val_accuracy: 0.7597 - val_loss: 0.5067
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8094 - loss: 0.4178 - val_accuracy: 0.7987 - val_loss: 0.5520
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8094 - loss: 0.4108 - val_accuracy: 0.7532 - val_loss: 0.5401
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8111 - loss: 0.4067 - val_accuracy: 0.7532 - val_loss: 0.5256
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8371 - loss: 0.3842 - val_accuracy: 0.7987 - val_loss: 0.5133
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3790 - val_accuracy: 0.7792 - val_loss: 0.5157
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3693 - val_accuracy: 0.7597 - val_loss: 0.6339
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3747 - val_accuracy: 0.7727 - val_loss: 0.5470
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3567 - val_accuracy: 0.7468 - val_loss: 0.5245
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3455 - val_accuracy: 0.7468 - val_loss: 0.5691
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3281 - val_accuracy: 0.7208 - val_loss: 0.5546
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3327 - val_accuracy: 0.7597 - val_loss: 0.5712
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3065 - val_accuracy: 0.7597 - val_loss: 0.5700
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3092 - val_accuracy: 0.7338 - val_loss: 0.6240
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2697 - val_accuracy: 0.7403 - val_loss: 0.8031
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.2766 - val_accuracy: 0.7662 - val_loss: 0.6622
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2509 - val_accuracy: 0.7792 - val_loss: 0.6403
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2596 - val_accuracy: 0.7468 - val_loss: 0.6418
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2550 - val_accuracy: 0.7338 - val_loss: 0.7170
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2424 - val_accuracy: 0.7532 - val_loss: 0.7043
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9121 - loss: 0.2184 - val_accuracy: 0.7078 - val_loss: 0.8600
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.1995 - val_accuracy: 0.6364 - val_loss: 1.3023
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2331 - val_accuracy: 0.7338 - val_loss: 0.8695
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9267 - loss: 0.1748 - val_accuracy: 0.7403 - val_loss: 0.9755
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1595 - val_accuracy: 0.7468 - val_loss: 0.9147
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9332 - loss: 0.1680 - val_accuracy: 0.7143 - val_loss: 0.8278
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9528 - loss: 0.1427 - val_accuracy: 0.7208 - val_loss: 0.9671
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9316 - loss: 0.1614 - val_accuracy: 0.7013 - val_loss: 0.9325
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9463 - loss: 0.1408 - val_accuracy: 0.7403 - val_loss: 1.0342
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1393 - val_accuracy: 0.7403 - val_loss: 0.9962
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9495 - loss: 0.1432 - val_accuracy: 0.6948 - val_loss: 1.0010
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0957 - val_accuracy: 0.7532 - val_loss: 1.1753
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.1049 - val_accuracy: 0.7338 - val_loss: 1.2160
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1670 - val_accuracy: 0.7403 - val_loss: 0.9243
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0633 - val_accuracy: 0.7208 - val_loss: 1.3436
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1219 - val_accuracy: 0.7273 - val_loss: 1.2287
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0783 - val_accuracy: 0.7013 - val_loss: 1.4240
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0649 - val_accuracy: 0.7792 - val_loss: 1.4582
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1119 - val_accuracy: 0.7338 - val_loss: 1.3399
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1147 - val_accuracy: 0.7143 - val_loss: 1.3562
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0448 - val_accuracy: 0.7143 - val_loss: 1.5394
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.0904 - val_accuracy: 0.6753 - val_loss: 1.4336
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0782 - val_accuracy: 0.7532 - val_loss: 1.3819
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.1158 - val_accuracy: 0.7143 - val_loss: 1.4614
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0425 - val_accuracy: 0.7338 - val_loss: 1.4121
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0338 - val_accuracy: 0.7273 - val_loss: 1.9297
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.0860 - val_accuracy: 0.6818 - val_loss: 1.6065
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0263 - val_accuracy: 0.6299 - val_loss: 2.0377
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0206 - val_accuracy: 0.7338 - val_loss: 1.9895
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0707 - val_accuracy: 0.7143 - val_loss: 1.9755
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0774 - val_accuracy: 0.7208 - val_loss: 1.8135
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0371 - val_accuracy: 0.7403 - val_loss: 1.7618
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0350 - val_accuracy: 0.7013 - val_loss: 1.9294
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0335 - val_accuracy: 0.7532 - val_loss: 1.9656
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0700 - val_accuracy: 0.7208 - val_loss: 1.8075
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0597 - val_accuracy: 0.7597 - val_loss: 1.8529
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0233 - val_accuracy: 0.7208 - val_loss: 1.9688
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0480 - val_accuracy: 0.7273 - val_loss: 1.9319
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0146 - val_accuracy: 0.7338 - val_loss: 1.9997
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0583 - val_accuracy: 0.7013 - val_loss: 1.7750
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0324 - val_accuracy: 0.6948 - val_loss: 1.7763
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0237 - val_accuracy: 0.7013 - val_loss: 2.1636
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0198 - val_accuracy: 0.7338 - val_loss: 2.1148
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0959 - val_accuracy: 0.6883 - val_loss: 1.9540
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0074 - val_accuracy: 0.7013 - val_loss: 2.0493
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0134 - val_accuracy: 0.6818 - val_loss: 2.1647
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.6948 - val_loss: 2.5873
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1388 - val_accuracy: 0.6753 - val_loss: 1.9725
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0047 - val_accuracy: 0.7078 - val_loss: 2.0026
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7208 - val_loss: 2.2476
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.6478e-04 - val_accuracy: 0.7273 - val_loss: 2.4759
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 3.6995e-04 - val_accuracy: 0.7273 - val_loss: 2.7082
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9642 - loss: 0.1482 - val_accuracy: 0.7532 - val_loss: 2.1241
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9870 - loss: 0.0563 - val_accuracy: 0.7013 - val_loss: 2.2353
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9935 - loss: 0.0163 - val_accuracy: 0.6753 - val_loss: 2.0975
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9902 - loss: 0.0509 - val_accuracy: 0.7273 - val_loss: 1.9743
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0319 - val_accuracy: 0.7532 - val_loss: 1.7838
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9935 - loss: 0.0338 - val_accuracy: 0.7532 - val_loss: 1.9731
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9886 - loss: 0.0344 - val_accuracy: 0.7078 - val_loss: 1.9441
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9886 - loss: 0.0316 - val_accuracy: 0.7468 - val_loss: 1.7928
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0038 - val_accuracy: 0.6623 - val_loss: 2.6885
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9853 - loss: 0.0512 - val_accuracy: 0.7273 - val_loss: 1.9821
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0054 - val_accuracy: 0.7662 - val_loss: 2.0123
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0105 - val_accuracy: 0.7468 - val_loss: 2.6001
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0597 - val_accuracy: 0.6818 - val_loss: 2.2151
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0496 - val_accuracy: 0.7727 - val_loss: 1.9767
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.7403 - val_loss: 2.0721
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0171 - val_accuracy: 0.7338 - val_loss: 2.0905
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0247 - val_accuracy: 0.7013 - val_loss: 2.5899

In [34]:
def build_model(hp):
  model = Sequential()
  counter = 0
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units'+str(i), min_value=8, max_value=128, step=8),
              activation = hp.Choice('activation'+ str(i), values=['relu', 'tanh', 'sigmoid']),
              input_dim = 8
              )
          )
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(
        Dense(
            hp.Int('units'+str(i), min_value=8, max_value=128, step=8),
            activation = hp.Choice('activation'+ str(i), values=['relu', 'tanh', 'sigmoid'])
          )
        )
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

    counter+=1

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta']),
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

In [43]:
tuner = kt.RandomSearch(build_model,
                        objective= 'val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='final')

Reloading Tuner from mydir/final/tuner0.json

In [44]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [45]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4,
 'units0': 112,
 'activation0': 'tanh',
 'dropout0': 0.7,
 'optimizer': 'sgd',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1}

In [46]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [47]:
model.fit(X_train,y_train, epochs=200, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6368 - loss: 0.6807 - val_accuracy: 0.6429 - val_loss: 0.6766
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 0.6765 - val_accuracy: 0.6429 - val_loss: 0.6739
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6482 - loss: 0.6735 - val_accuracy: 0.6429 - val_loss: 0.6710
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6702 - val_accuracy: 0.6429 - val_loss: 0.6689
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6683 - val_accuracy: 0.6429 - val_loss: 0.6671
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6564 - loss: 0.6637 - val_accuracy: 0.6429 - val_loss: 0.6651
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6635 - val_accuracy: 0.6429 - val_loss: 0.6632
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6531 - loss: 0.6626 - val_accuracy: 0.6429 - val_loss: 0.6618
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6531 - loss: 0.6587 - val_accuracy: 0.6429 - val_loss: 0.6604
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6587 - val_accuracy: 0.6429 - val_loss: 0.6592
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6565 - val_accuracy: 0.6429 - val_loss: 0.6581
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6540 - val_accuracy: 0.6429 - val_loss: 0.6570
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6515 - loss: 0.6535 - val_accuracy: 0.6429 - val_loss: 0.6562
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6531 - loss: 0.6532 - val_accuracy: 0.6429 - val_loss: 0.6554
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6531 - loss: 0.6534 - val_accuracy: 0.6429 - val_loss: 0.6546
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6547 - loss: 0.6506 - val_accuracy: 0.6429 - val_loss: 0.6538
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6531 - loss: 0.6494 - val_accuracy: 0.6429 - val_loss: 0.6530
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6531 - loss: 0.6506 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6493 - val_accuracy: 0.6429 - val_loss: 0.6517
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6472 - val_accuracy: 0.6429 - val_loss: 0.6512
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6466 - val_accuracy: 0.6429 - val_loss: 0.6508
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6455 - val_accuracy: 0.6429 - val_loss: 0.6503
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6449 - val_accuracy: 0.6429 - val_loss: 0.6498
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6467 - val_accuracy: 0.6429 - val_loss: 0.6493
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6444 - val_accuracy: 0.6429 - val_loss: 0.6489
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6439 - val_accuracy: 0.6429 - val_loss: 0.6485
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6437 - val_accuracy: 0.6429 - val_loss: 0.6480
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6434 - val_accuracy: 0.6429 - val_loss: 0.6476
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6427 - val_accuracy: 0.6429 - val_loss: 0.6471
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6430 - val_accuracy: 0.6429 - val_loss: 0.6467
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6412 - val_accuracy: 0.6429 - val_loss: 0.6462
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6419 - val_accuracy: 0.6429 - val_loss: 0.6459
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6394 - val_accuracy: 0.6429 - val_loss: 0.6454
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6402 - val_accuracy: 0.6429 - val_loss: 0.6448
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6408 - val_accuracy: 0.6429 - val_loss: 0.6443
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6392 - val_accuracy: 0.6429 - val_loss: 0.6436
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6406 - val_accuracy: 0.6429 - val_loss: 0.6431
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6388 - val_accuracy: 0.6429 - val_loss: 0.6426
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6531 - loss: 0.6381 - val_accuracy: 0.6429 - val_loss: 0.6419
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6389 - val_accuracy: 0.6429 - val_loss: 0.6413
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6395 - val_accuracy: 0.6429 - val_loss: 0.6407
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6402 - val_accuracy: 0.6429 - val_loss: 0.6402
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6351 - val_accuracy: 0.6429 - val_loss: 0.6394
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6341 - val_accuracy: 0.6429 - val_loss: 0.6386
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6355 - val_accuracy: 0.6429 - val_loss: 0.6378
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6333 - val_accuracy: 0.6429 - val_loss: 0.6369
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6329 - val_accuracy: 0.6429 - val_loss: 0.6359
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6334 - val_accuracy: 0.6429 - val_loss: 0.6349
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6320 - val_accuracy: 0.6429 - val_loss: 0.6338
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6326 - val_accuracy: 0.6429 - val_loss: 0.6328
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6294 - val_accuracy: 0.6429 - val_loss: 0.6318
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6323 - val_accuracy: 0.6429 - val_loss: 0.6309
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6317 - val_accuracy: 0.6429 - val_loss: 0.6298
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6307 - val_accuracy: 0.6429 - val_loss: 0.6286
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6273 - val_accuracy: 0.6429 - val_loss: 0.6272
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6262 - val_accuracy: 0.6429 - val_loss: 0.6258
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6228 - val_accuracy: 0.6429 - val_loss: 0.6239
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6244 - val_accuracy: 0.6429 - val_loss: 0.6223
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6252 - val_accuracy: 0.6429 - val_loss: 0.6208
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6564 - loss: 0.6271 - val_accuracy: 0.6429 - val_loss: 0.6198
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6231 - val_accuracy: 0.6429 - val_loss: 0.6182
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6214 - val_accuracy: 0.6429 - val_loss: 0.6165
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6182 - val_accuracy: 0.6429 - val_loss: 0.6143
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6175 - val_accuracy: 0.6429 - val_loss: 0.6124
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6192 - val_accuracy: 0.6429 - val_loss: 0.6105
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6145 - val_accuracy: 0.6429 - val_loss: 0.6082
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6564 - loss: 0.6129 - val_accuracy: 0.6429 - val_loss: 0.6060
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6122 - val_accuracy: 0.6429 - val_loss: 0.6035
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6058 - val_accuracy: 0.6429 - val_loss: 0.6005
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6044 - val_accuracy: 0.6429 - val_loss: 0.5973
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6040 - val_accuracy: 0.6429 - val_loss: 0.5944
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6596 - loss: 0.6043 - val_accuracy: 0.6429 - val_loss: 0.5916
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6678 - loss: 0.5929 - val_accuracy: 0.6429 - val_loss: 0.5881
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.5935 - val_accuracy: 0.6429 - val_loss: 0.5847
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.5899 - val_accuracy: 0.6429 - val_loss: 0.5806
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.5897 - val_accuracy: 0.6429 - val_loss: 0.5771
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.5888 - val_accuracy: 0.6429 - val_loss: 0.5739
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6743 - loss: 0.5827 - val_accuracy: 0.6429 - val_loss: 0.5701
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6743 - loss: 0.5770 - val_accuracy: 0.6429 - val_loss: 0.5658
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.5842 - val_accuracy: 0.6429 - val_loss: 0.5621
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.5786 - val_accuracy: 0.6429 - val_loss: 0.5576
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.5747 - val_accuracy: 0.6494 - val_loss: 0.5540
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6726 - loss: 0.5833 - val_accuracy: 0.6623 - val_loss: 0.5505
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5639 - val_accuracy: 0.6623 - val_loss: 0.5463
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.5657 - val_accuracy: 0.6688 - val_loss: 0.5421
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6922 - loss: 0.5739 - val_accuracy: 0.6753 - val_loss: 0.5388
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6743 - loss: 0.5677 - val_accuracy: 0.6818 - val_loss: 0.5355
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7003 - loss: 0.5669 - val_accuracy: 0.7013 - val_loss: 0.5323
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6906 - loss: 0.5554 - val_accuracy: 0.7208 - val_loss: 0.5286
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6873 - loss: 0.5532 - val_accuracy: 0.7273 - val_loss: 0.5254
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6889 - loss: 0.5632 - val_accuracy: 0.7273 - val_loss: 0.5232
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7085 - loss: 0.5702 - val_accuracy: 0.7273 - val_loss: 0.5215
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7052 - loss: 0.5592 - val_accuracy: 0.7273 - val_loss: 0.5188
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6906 - loss: 0.5392 - val_accuracy: 0.7468 - val_loss: 0.5154
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7150 - loss: 0.5440 - val_accuracy: 0.7532 - val_loss: 0.5122
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7134 - loss: 0.5533 - val_accuracy: 0.7662 - val_loss: 0.5106
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7264 - loss: 0.5406 - val_accuracy: 0.7792 - val_loss: 0.5076
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5637 - val_accuracy: 0.7792 - val_loss: 0.5068
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5496 - val_accuracy: 0.7792 - val_loss: 0.5048
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.5599 - val_accuracy: 0.7727 - val_loss: 0.5041
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5424 - val_accuracy: 0.7792 - val_loss: 0.5027
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5468 - val_accuracy: 0.7792 - val_loss: 0.5011
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.5568 - val_accuracy: 0.7792 - val_loss: 0.5009
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5519 - val_accuracy: 0.7857 - val_loss: 0.5000
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.5492 - val_accuracy: 0.7922 - val_loss: 0.4988
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5286 - val_accuracy: 0.7792 - val_loss: 0.4962
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7134 - loss: 0.5405 - val_accuracy: 0.7857 - val_loss: 0.4944
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5343 - val_accuracy: 0.7922 - val_loss: 0.4939
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5406 - val_accuracy: 0.7922 - val_loss: 0.4931
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5322 - val_accuracy: 0.7922 - val_loss: 0.4920
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5181 - val_accuracy: 0.7857 - val_loss: 0.4906
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5298 - val_accuracy: 0.7857 - val_loss: 0.4892
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5151 - val_accuracy: 0.7857 - val_loss: 0.4874
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5175 - val_accuracy: 0.7857 - val_loss: 0.4861
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5152 - val_accuracy: 0.7857 - val_loss: 0.4847
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5398 - val_accuracy: 0.7857 - val_loss: 0.4836
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5256 - val_accuracy: 0.7857 - val_loss: 0.4835
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5457 - val_accuracy: 0.7857 - val_loss: 0.4834
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5292 - val_accuracy: 0.7857 - val_loss: 0.4825
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5513 - val_accuracy: 0.7857 - val_loss: 0.4823
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5283 - val_accuracy: 0.7922 - val_loss: 0.4814
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5233 - val_accuracy: 0.7857 - val_loss: 0.4816
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5369 - val_accuracy: 0.7857 - val_loss: 0.4834
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5213 - val_accuracy: 0.7857 - val_loss: 0.4823
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5319 - val_accuracy: 0.7792 - val_loss: 0.4821
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5402 - val_accuracy: 0.7792 - val_loss: 0.4816
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5091 - val_accuracy: 0.7857 - val_loss: 0.4799
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5233 - val_accuracy: 0.7922 - val_loss: 0.4788
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5235 - val_accuracy: 0.7792 - val_loss: 0.4793
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5275 - val_accuracy: 0.7857 - val_loss: 0.4794
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5223 - val_accuracy: 0.7987 - val_loss: 0.4783
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5113 - val_accuracy: 0.7922 - val_loss: 0.4779
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5284 - val_accuracy: 0.7987 - val_loss: 0.4785
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5206 - val_accuracy: 0.7922 - val_loss: 0.4796
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5056 - val_accuracy: 0.7987 - val_loss: 0.4788
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5361 - val_accuracy: 0.7987 - val_loss: 0.4789
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5073 - val_accuracy: 0.7987 - val_loss: 0.4786
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5168 - val_accuracy: 0.7987 - val_loss: 0.4767
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5366 - val_accuracy: 0.7987 - val_loss: 0.4777
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5362 - val_accuracy: 0.7987 - val_loss: 0.4786
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5081 - val_accuracy: 0.7987 - val_loss: 0.4785
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5178 - val_accuracy: 0.7922 - val_loss: 0.4791
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5034 - val_accuracy: 0.7922 - val_loss: 0.4783
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5283 - val_accuracy: 0.7922 - val_loss: 0.4786
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5235 - val_accuracy: 0.7922 - val_loss: 0.4780
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5195 - val_accuracy: 0.7857 - val_loss: 0.4771
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5039 - val_accuracy: 0.7922 - val_loss: 0.4759
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5264 - val_accuracy: 0.7857 - val_loss: 0.4763
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.5001 - val_accuracy: 0.7857 - val_loss: 0.4760
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5207 - val_accuracy: 0.7857 - val_loss: 0.4753
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5082 - val_accuracy: 0.7922 - val_loss: 0.4762
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5105 - val_accuracy: 0.7922 - val_loss: 0.4752
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5077 - val_accuracy: 0.7922 - val_loss: 0.4752
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5328 - val_accuracy: 0.7922 - val_loss: 0.4766
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5168 - val_accuracy: 0.7922 - val_loss: 0.4763
Epoch 162/200